### ISSUE TITLE
極度Vuex使用（しなさい）

### ISSUE THREAD

**Issue by TinyKitten** [neirowork/Librarian#15]
<img width="534" alt="スクリーンショット 2019-03-11 1 09 49" src="https://user-images.githubusercontent.com/32848922/54087824-83657600-439a-11e9-9ab6-c3b2bf635fa8.png">
methodsでVuex叩いてるならそもそもVuexのActionsに書いたほうがよくねって趣がある（適当）

**Comment by nirot1r** [comment]
#16
